achievementData = {
	name = "First in... Line?",
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"act5", "act10", "act25", "act50", "hard", "oneshot", "timed", "multi", "heckled", "multitasker"},
	achievements = {
		{
			id = "act5",
			name = "First Audition",
			description = "Reach Act 5 in Arcade Mode (easy)",
			isSecret = false,
			progressMax = 5,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "act10",
			name = "Backup Actor",
			description = "Reach Act 10 in Arcade Mode (easy)",
			isSecret = false,
			progressMax = 10,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "act25",
			name = "Lead Role",
			description = "Reach Act 25 in Arcade Mode (easy)",
			isSecret = false,
			progressMax = 25,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "act50",
			name = "Broadway Star",
			description = "Reach Act 50 in Arcade Mode (easy)",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hard",
			name = "In the Limelight",
			description = "Unlock Hard difficulty",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "oneshot",
			name = "One-Shot Mode",
			description = "Unlock One-Shot Mode",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "timed",
			name = "Timed Mode",
			description = "Unlock Timed Mode",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "multi",
			name = "Co-Star",
			description = "Try a round of Multi Mode",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "heckled",
			name = "Oh, Brother",
			description = "Get heckled",
			isSecret = true,
			scoreValue = 0,
		},
		{
			id = "multitasker",
			name = "Multitasker",
			description = "Play a round with all control options enabled",
			isSecret = true,
			scoreValue = 0,
		},
	}
}